name: Continuous Integration

on:
  pull_request:
  push:


jobs:
  test:
    name: sbt test on ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Tabby OSS Cad Suite (from YosysHQ)
        uses: YosysHQ/setup-oss-cad-suite@v1
        with:
          osscadsuite-version: '2021-11-09'
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Test
        run: sbt test
